/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorventa.igu;

import com.mycompany.gestorventa.entidades.Producto;
import com.mycompany.gestorventa.logica.ControlLogica;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ariel
 */
public class Venta extends javax.swing.JFrame {
    int precioTotal;
    ArrayList<Producto> listaCompra = new ArrayList();
    
    public Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        txtBuscador = new javax.swing.JTextField();
        JScrollPanel = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        txtPrecioTotal = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAñadirCarrito = new javax.swing.JButton();
        btnVenderProductos = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtBuscador.setText("jTextField1");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JScrollPanel.setViewportView(tablaProductos);

        txtPrecioTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPrecioTotal.setText("$0");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAñadirCarrito.setText("Añadir");
        btnAñadirCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirCarritoActionPerformed(evt);
            }
        });

        btnVenderProductos.setText("Vender");
        btnVenderProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAñadirCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnVenderProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnAñadirCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVenderProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       //obtiene el nombre del producto a buscar
        String texto = txtBuscador.getText();
        //llama a la funcion buscar y le pasa el nombre del producto a buscar
       buscador(texto);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnAñadirCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirCarritoActionPerformed
        //Crea una variable Producto
        Producto producto;
        //Crea una variable para conectar con la logica
        ControlLogica varLogica = new ControlLogica();
        //Obtiene el num de la fila del produto
        int i = tablaProductos.getSelectedRow();
        //Obtiene el num de la columna del produto
        int j = tablaProductos.getSelectedColumn();
        //Obtiene el id del producto
        int id = (int) tablaProductos.getValueAt(i, j);
        //busca el producto en la base de datos
        producto = varLogica.buscarProducto(id);
        //añade el producto al carrito de compra
        listaCompra.add(producto);
        //Quita un producto del stock
        producto.setCantidad(producto.getCantidad()-1);
        varLogica.modificarProducto(producto);
        //suma los precios unitarios de los productos seleccionados
        precioTotal +=  producto.getPrecioUnit();
        //setea el precio total de la compra
        txtPrecioTotal.setText("$"+precioTotal+"");
        
    }//GEN-LAST:event_btnAñadirCarritoActionPerformed

    private void btnVenderProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderProductosActionPerformed
        txtPrecioTotal.setText("$0");
        VentaConfirmacion ventaConfir = new VentaConfirmacion();
        ventaConfir.setVisible(true);
        ventaConfir.setLocationRelativeTo(null);
        ventaConfir.cargarListaCompra(listaCompra);
    }//GEN-LAST:event_btnVenderProductosActionPerformed

    public void cargarTabla(){
        //Crea una variable para conectar con la logica
        ControlLogica varLogica = new ControlLogica();
        //Crea una tabla
        DefaultTableModel modeloTabla = new DefaultTableModel(){ 
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        //Insercion de los titulos a las columnas de la tabla
        String titulo[] = {"ID","nombre","Precio","Cantidad"};
        modeloTabla.setColumnIdentifiers(titulo);
        
        //recupera la lista de productos de la base de datos
        List<Producto> listaProductos = varLogica.buscarProductos();
        //Recorre la lista de tareas y las añade a las filas
        if(listaProductos != null){
            for(Producto productos: listaProductos){
                Object[] objeto = {productos.getId(),productos.getNombre(),productos.getPrecioUnit(),productos.getCantidad()};
                modeloTabla.addRow(objeto);
            }
        }
        //Se agrega la lista de tareas a la tabla
        tablaProductos.setModel(modeloTabla);
    }
    
    public void buscador(String producto){
        //Crea una variable para conectar con la logica
        ControlLogica varLogica = new ControlLogica();
        //Crea una tabla
        DefaultTableModel modeloTabla = new DefaultTableModel(){ 
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        //Insercion de los titulos a las columnas de la tabla
        String titulo[] = {"ID","nombre","Precio","Cantidad"};
        modeloTabla.setColumnIdentifiers(titulo);
        
        //Busca y almacena en la variable una lista de productos, los cuales son buscados por nombre
        List<Producto> listaProductos = varLogica.buscadorProductos(producto);
        
        //Recorre la lista de tareas y las añade a las filas
        if(listaProductos != null){
            for(Producto productos: listaProductos){
                Object[] objeto = {productos.getId(),productos.getNombre(),productos.getPrecioUnit(),productos.getCantidad()};
                modeloTabla.addRow(objeto);
            }
        }
        //Se agrega la lista de tareas a la tabla
        tablaProductos.setModel(modeloTabla);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPanel;
    private javax.swing.JButton btnAñadirCarrito;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVenderProductos;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtPrecioTotal;
    // End of variables declaration//GEN-END:variables
}
