/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import entidad.Grupo;
import entidad.Tarea;
import java.util.ArrayList;

import servicios.TareaServicios;

/**
 *
 * @author Ariel
 */
public class CrearTarea extends javax.swing.JFrame {

    /**
     * Creates new form CrearTarea
     */
    public CrearTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldTarea = new javax.swing.JTextField();
        textFieldNota = new javax.swing.JTextField();
        textFieldDia = new javax.swing.JTextField();
        textFieldHora = new javax.swing.JTextField();
        CrearTarea = new javax.swing.JButton();
        LimpiarTexto = new javax.swing.JButton();
        textFieldGrupo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Tarea");

        jLabel2.setText("Tarea:");

        jLabel3.setText("Nota:");

        jLabel4.setText("Dia:");

        jLabel5.setText("Hora:");

        jLabel6.setText("Grupo:");

        textFieldTarea.setText("ingrese el texto");
        textFieldTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTareaActionPerformed(evt);
            }
        });

        textFieldNota.setText("ingrese el texto");
        textFieldNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNotaActionPerformed(evt);
            }
        });

        textFieldDia.setText("ingrese el texto");
        textFieldDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDiaActionPerformed(evt);
            }
        });

        textFieldHora.setText("ingrese el texto");
        textFieldHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldHoraActionPerformed(evt);
            }
        });

        CrearTarea.setText("Aceptar");
        CrearTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearTareaActionPerformed(evt);
            }
        });

        LimpiarTexto.setText("Limpiar");
        LimpiarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarTextoActionPerformed(evt);
            }
        });

        textFieldGrupo.setText("Ingrese el texto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LimpiarTexto)
                        .addGap(62, 62, 62)
                        .addComponent(CrearTarea))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(textFieldNota)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textFieldHora)
                                .addComponent(textFieldDia, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(textFieldTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimpiarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void textFieldTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTareaActionPerformed

    private void textFieldNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNotaActionPerformed

    private void textFieldHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldHoraActionPerformed

    private void textFieldDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDiaActionPerformed
   
    private void LimpiarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarTextoActionPerformed
        //Realiza la limpieza de los campos de texto
        textFieldTarea.setText("");
        textFieldHora.setText("");
        textFieldDia.setText("");
        textFieldNota.setText("");
        textFieldGrupo.setText("");
    }//GEN-LAST:event_LimpiarTextoActionPerformed
     
    private void CrearTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearTareaActionPerformed
        //Llama a la interfaz de la lista de tareas
        TareaAcciones cargarListaTarea = new TareaAcciones();
        //Inicializa un arraylist de tareas
        ArrayList<Tarea> listaTareas = new ArrayList();
        //Objeto tarea
        Tarea tareaCreada = new Tarea();
      
        //Servicios
        TareaServicios serv = new TareaServicios();

        //Seteo de datos a la tarea
        tareaCreada.setDescripTarea(textFieldTarea.getText());
        tareaCreada.setNotaAdic(textFieldNota.getText());
        tareaCreada.setDia(textFieldDia.getText());
        int hora = Integer.parseInt(textFieldHora.getText());
        tareaCreada.setHora(hora);
        tareaCreada.setGrupo(textFieldGrupo.getText());
        
        //crea la tarea en la base de datos
        serv.crearTarea(tareaCreada);
        //Llama a la lista de tareas
        cargarListaTarea.setVisible(true);
        cargarListaTarea.setLocationRelativeTo(null);
    }//GEN-LAST:event_CrearTareaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearTarea;
    private javax.swing.JButton LimpiarTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldDia;
    private javax.swing.JTextField textFieldGrupo;
    private javax.swing.JTextField textFieldHora;
    private javax.swing.JTextField textFieldNota;
    private javax.swing.JTextField textFieldTarea;
    // End of variables declaration//GEN-END:variables

}
